[package]
name = "teeline"
version = "0.1.0"
authors = ["Timo Sulg <timgluz@gmail.com>"]
edition = "2018"

[lib]
name = "teeline"
path = "src/lib.rs"

[[bin]]
name = "bin"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
rand = "0.7.3"
