app = "teeline-api"
primary_region = "ams"

[build]
dockerfile = "teeline-api/Dockerfile"

[env]
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
path = "/api/v1/health"
timeout = "5s"
