package teeline:solver@0.1.0;

interface types {
    record city {
        id: u32,
        x: f32,
        y: f32,
    }

    record solve-options {
        epochs: u32,
        platoo-epochs: u32,
        cooling-rate: f32,
        max-temperature: f32,
        min-temperature: f32,
        mutation-probability: f32,
        n-elite: u32,
        n-nearest: u32,
    }

    record solution {
        total: f32,
        route: list<u32>,
    }
}

world solver {
    use types.{city, solve-options, solution};

    export solve: func(
        solver: string,
        cities: list<city>,
        options: solve-options,
    ) -> result<solution, string>;

    export parse-and-solve: func(
        solver: string,
        input: string,
        options: solve-options,
    ) -> result<solution, string>;
}
